environment:
   domain: "dockerlab.local"
   #dtrurl: "https://dtr.dockerlab.local:7443"
   ucpip: "10.0.100.10"
   ucpuser: "admin"
   ucppasswd: "changeme"
   ucpurl:  "https://10.0.100.10:8443"
   dtrurl: "https://10.0.100.10:7443"
   ucpfqdn: "ucp.dockerlab.local"
   dtrfqdn: "dtr.dockerlab.local"

boxes:
- name: "ucp-manager"
  fqdn: "ucp-manager.dockerlab.local"
  managementip: "10.0.100.10"
  storageip: "192.168.100.10"
  mem: "5000"
  cpu: "1"
  ucprole: "master"
  dtr:  true


#- name: "ucp-replica1"
#  fqdn: "ucp-replica1.dockerlab.local"
#  managementip: "10.0.100.11"
#  storageip: "192.168.100.11"
#  mem: "3072"
#  cpu: "1"
#  ucprole: "replica"
#
#- name: "ucp-replica2"
#  fqdn: "ucp-replica2.dockerlab.local"
#  managementip: "10.0.100.12"
#  storageip: "192.168.100.12"
#  mem: "3072"
#  cpu: "1"
#  ucprole: "replica"

- name: "ucp-node1"
  fqdn: "ucp-node1.dockerlab.local"
  managementip: "10.0.100.13"
  storageip: "192.168.100.13"
  mem: "2048"
  cpu: "1"
  ucprole: "node"

#- name: "ucp-node2"
#  fqdn: "ucp-node2.dockerlab.local"
#  managementip: "10.0.100.14"
#  storageip: "192.168.100.14"
#  mem: "2048"
#  cpu: "1"
#  ucprole: "node"

- name: "ucp-client"
  fqdn: "ucp-client.dockerlab.local"
  managementip: "10.0.100.20"
  storageip: "192.168.100.20"
  mem: "1560"
  cpu: "1"
  ucprole: "client"
